
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ShasanN1
 */
public class Calculator extends javax.swing.JFrame {

    

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
       
    }
    float N=0,N1=0;
    int opt; 
    void func(int a)
    {
        switch(opt)
        {
            case 1:N+=N1;N1=0;opt=a;break;
            case 2:N-=N1;N1=0;opt=a;break;
            case 3:N*=N1;N1=0;opt=a;break;
            case 4:N/=N1;N1=0;opt=a;break;
        }
    }
void minus()
{
    if(txt.getText().isEmpty())
    {  
        opt=2;
        String a=lbl.getText();
        int a1=a.length();
        a=a.substring(0,a1-1)+"-";
        lbl.setText(a);
    }
    if(N!=0)
    {
        N1=Float.parseFloat(txt.getText());
        func(2);
        lbl.setText(lbl.getText()+txt.getText()+"-");
        txt.setText("");
    }
    else
    {
        N=Float.parseFloat(txt.getText());
        lbl.setText(txt.getText()+"-");
        txt.setText("");
        opt=2;
    }
    txt.grabFocus();
}
void add()
{
    if(txt.getText().isEmpty())
    {   
        opt=1;
        String a=lbl.getText();
        int a1=a.length();
        a=a.substring(0, a1-1)+"+";
        lbl.setText(a);
    }if(N!=0)
    {
        N1=Float.parseFloat(txt.getText());
        func(1);
        lbl.setText(lbl.getText()+txt.getText()+"+");
        txt.setText("");
    }
    else
    {
        N=Float.parseFloat(txt.getText());
        lbl.setText(txt.getText()+"+");
        txt.setText("");
        opt=1;
    }
    txt.grabFocus();
}
void divide()
{
    if(txt.getText().isEmpty())
    {   
        opt=4;
        String a=lbl.getText();
        int a1=a.length();
        a=a.substring(0, a1-1)+"/";
        lbl.setText(a);
    }if(N!=0)
    {
        N1=Float.parseFloat(txt.getText());
        func(4);
        lbl.setText(lbl.getText()+txt.getText()+"/");
        txt.setText("");
    }
    else
    {
        N=Float.parseFloat(txt.getText());
        lbl.setText(txt.getText()+"/");
        txt.setText("");
        opt=4;
    }
    txt.grabFocus(); 
}
void multiply()
{
    if(txt.getText().isEmpty())
    {   
        opt=3;
        String a=lbl.getText();
        int a1=a.length();
        a=a.substring(0, a1-1)+"*";
        lbl.setText(a);
    }if(N!=0)
    {
        N1=Float.parseFloat(txt.getText());
        func(3);
        lbl.setText(lbl.getText()+txt.getText()+"*");
        txt.setText("");
    }
    else
    {
        N=Float.parseFloat(txt.getText());
        lbl.setText(txt.getText()+"*");
        txt.setText("");
        opt=3;
    }
    txt.grabFocus();
}
void equalto()
{
    if(txt.getText().isEmpty())
    {
        lbl.setText("");
        txt.setText(""+N); 
        N=0;
    }
    else
    {
        N1=Float.parseFloat(txt.getText());
        func(opt);
        lbl.setText("");
        txt.setText(""+N); 
        N=0;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        cmdb = new javax.swing.JButton();
        cmds = new javax.swing.JButton();
        cmd1 = new javax.swing.JButton();
        cmda = new javax.swing.JButton();
        cmd8 = new javax.swing.JButton();
        cmd9 = new javax.swing.JButton();
        cmdp = new javax.swing.JButton();
        cmd3 = new javax.swing.JButton();
        cmd7 = new javax.swing.JButton();
        cmdm = new javax.swing.JButton();
        cmdac = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        cmd0 = new javax.swing.JButton();
        cmdd = new javax.swing.JButton();
        cmd4 = new javax.swing.JButton();
        cmd6 = new javax.swing.JButton();
        cmde = new javax.swing.JButton();
        cmd5 = new javax.swing.JButton();
        cmd2 = new javax.swing.JButton();

        jButton13.setText("7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        cmdb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdb.setText("<html> <head><title></title> <body> <pre> ← </pre> </body> </html>");
        cmdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbActionPerformed(evt);
            }
        });
        cmdb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmdbFocusGained(evt);
            }
        });

        cmds.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmds.setText("-");
        cmds.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmdsFocusGained(evt);
            }
        });

        cmd1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmd1.setText("1");
        cmd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd1ActionPerformed(evt);
            }
        });

        cmda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmda.setText("+");
        cmda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdaActionPerformed(evt);
            }
        });
        cmda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmdaFocusGained(evt);
            }
        });

        cmd8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmd8.setText("8");
        cmd8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd8ActionPerformed(evt);
            }
        });

        cmd9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmd9.setText("9");
        cmd9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd9ActionPerformed(evt);
            }
        });

        cmdp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdp.setText(".");
        cmdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpActionPerformed(evt);
            }
        });
        cmdp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmdpFocusGained(evt);
            }
        });

        cmd3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmd3.setText("3");
        cmd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd3ActionPerformed(evt);
            }
        });

        cmd7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmd7.setText("7");
        cmd7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd7ActionPerformed(evt);
            }
        });

        cmdm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdm.setText("*");
        cmdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdmActionPerformed(evt);
            }
        });
        cmdm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmdmFocusGained(evt);
            }
        });

        cmdac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdac.setText(" All Clear");
        cmdac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdacActionPerformed(evt);
            }
        });
        cmdac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmdacFocusGained(evt);
            }
        });

        txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKeyTyped(evt);
            }
        });

        cmd0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmd0.setText("0");
        cmd0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd0ActionPerformed(evt);
            }
        });

        cmdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdd.setText("/");
        cmdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmddFocusGained(evt);
            }
        });

        cmd4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmd4.setText("4");
        cmd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd4ActionPerformed(evt);
            }
        });

        cmd6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmd6.setText("6");
        cmd6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd6ActionPerformed(evt);
            }
        });

        cmde.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmde.setText("=");
        cmde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdeActionPerformed(evt);
            }
        });
        cmde.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmdeFocusGained(evt);
            }
        });

        cmd5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmd5.setText("5");
        cmd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd5ActionPerformed(evt);
            }
        });

        cmd2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmd2.setText("2");
        cmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cmd7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmd8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmd9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cmd4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmd5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmd6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmd1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmd2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmd3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmd0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmdp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmde, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmds, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmdac, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdb)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmd0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmde, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmds, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdac, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmdpFocusGained
    if(txt.getText().isEmpty())
        txt.setText(""+".");
    else
    {
        int a=Integer.parseInt(txt.getText());
        float b=Float.parseFloat(txt.getText());
        if(a==b)
            txt.setText(txt.getText()+".");   
        else
            txt.setText(txt.getText());
    }
    txt.grabFocus();
    }//GEN-LAST:event_cmdpFocusGained

    private void cmdeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmdeFocusGained
    equalto();
    }//GEN-LAST:event_cmdeFocusGained
      
    private void cmdacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmdacFocusGained
    
    }//GEN-LAST:event_cmdacFocusGained

    private void cmdbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmdbFocusGained
     
    }//GEN-LAST:event_cmdbFocusGained

    private void cmdsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmdsFocusGained
    minus();  
    }//GEN-LAST:event_cmdsFocusGained

    private void cmdaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmdaFocusGained
    add();
    }//GEN-LAST:event_cmdaFocusGained

    private void cmddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmddFocusGained
    divide();
    }//GEN-LAST:event_cmddFocusGained

    private void cmdmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmdmFocusGained
    multiply(); 
    }//GEN-LAST:event_cmdmFocusGained

    private void txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyTyped
    if(evt.getKeyChar()==KeyEvent.VK_1)
    {
        evt.consume();
        cmd1.doClick();
    }
    if(evt.getKeyChar()==KeyEvent.VK_2)
    {
        evt.consume();
        cmd2.doClick();
    }
    if(evt.getKeyChar()==KeyEvent.VK_3)
    {
        evt.consume();
        cmd3.doClick();
    }
    if(evt.getKeyChar()==KeyEvent.VK_4)
    {
        evt.consume();
        cmd4.doClick();
    }
    if(evt.getKeyChar()==KeyEvent.VK_5)
    {
        evt.consume();
        cmd5.doClick();
    }
    if(evt.getKeyChar()==KeyEvent.VK_6)
    {
        evt.consume();
        cmd6.doClick();
    }
    if(evt.getKeyChar()==KeyEvent.VK_7)
    {
        evt.consume();
        cmd7.doClick();
    }
    if(evt.getKeyChar()==KeyEvent.VK_8)
    {
        evt.consume();
        cmd8.doClick();
    }
    if(evt.getKeyChar()==KeyEvent.VK_9)
    {
        evt.consume();
        cmd9.doClick();
    }
    if(evt.getKeyChar()==KeyEvent.VK_0)
    {
        evt.consume();
        cmd0.doClick();
    }
    if(evt.getKeyChar()==KeyEvent.VK_PLUS || evt.getKeyChar()==KeyEvent.VK_ADD)
    { 
        evt.consume();
        add();
    }
    if(evt.getKeyChar()==KeyEvent.VK_MINUS || evt.getKeyChar()==KeyEvent.VK_SUBTRACT)    
    {
        evt.consume();
        minus();
    }
    if(evt.getKeyChar()==KeyEvent.VK_ASTERISK || evt.getKeyChar()==KeyEvent.VK_MULTIPLY)
    {
        evt.consume();
        multiply();
    }
    if(evt.getKeyChar()==KeyEvent.VK_BACK_SLASH || evt.getKeyChar()==KeyEvent.VK_DIVIDE)
    {
        evt.consume();
        divide();
    }
    if(evt.getKeyChar()==KeyEvent.VK_ENTER)
    {
        evt.consume();
        equalto();
    }
    
    }//GEN-LAST:event_txtKeyTyped

    private void cmd7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd7ActionPerformed
    String s="";
    s =txt.getText();
    txt.setText(s+"7");
    txt.grabFocus();
    }//GEN-LAST:event_cmd7ActionPerformed

    private void cmd8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd8ActionPerformed
    String s="";
    s =txt.getText();
    txt.setText(s+"8");
    txt.grabFocus();
    }//GEN-LAST:event_cmd8ActionPerformed

    private void cmd9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd9ActionPerformed
    String s="";
    s =txt.getText();
    txt.setText(s+"9");
    txt.grabFocus();
    }//GEN-LAST:event_cmd9ActionPerformed

    private void cmd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd4ActionPerformed
    String s="";
    s =txt.getText();
    txt.setText(s+"4");
    txt.grabFocus();
    }//GEN-LAST:event_cmd4ActionPerformed

    private void cmd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd5ActionPerformed
    String s="";
    s =txt.getText();
    txt.setText(s+5);
    txt.grabFocus();
    }//GEN-LAST:event_cmd5ActionPerformed

    private void cmd6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd6ActionPerformed
    String s="";
    s =txt.getText();
    txt.setText(s+6);
    txt.grabFocus(); 
    }//GEN-LAST:event_cmd6ActionPerformed

    private void cmd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd1ActionPerformed
    String s="";
    s =txt.getText();
    txt.setText(s+1);
    txt.grabFocus();  
    }//GEN-LAST:event_cmd1ActionPerformed

    private void cmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd2ActionPerformed
    String s="";
    s =txt.getText();
    txt.setText(s+2);
    txt.grabFocus();  
    }//GEN-LAST:event_cmd2ActionPerformed

    private void cmd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd3ActionPerformed
    String s="";
    s =txt.getText();
    txt.setText(s+3);
    txt.grabFocus();
    }//GEN-LAST:event_cmd3ActionPerformed

    private void cmd0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd0ActionPerformed
    String s="";
    s =txt.getText();
    txt.setText(s+0);
    txt.grabFocus();
    }//GEN-LAST:event_cmd0ActionPerformed

    private void cmdacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdacActionPerformed
    lbl.setText("");
    txt.setText("");
    N=0;N1=0;
    txt.grabFocus();
    }//GEN-LAST:event_cmdacActionPerformed

    private void cmdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpActionPerformed
    /*int a=Integer.parseInt(txt.getText());
    float b=Float.parseFloat(txt.getText());
    if(a!=b)
        txt.setText(txt.getText()+".");*/
    }//GEN-LAST:event_cmdpActionPerformed

    private void cmdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdeActionPerformed
    
    }//GEN-LAST:event_cmdeActionPerformed

    private void cmdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbActionPerformed
    if(txt.getText().length()!=0)
        txt.setText(txt.getText().substring(0,txt.getText().length()-1));
    else
        txt.setText("");   
    }//GEN-LAST:event_cmdbActionPerformed

    private void cmdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdaActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_cmdaActionPerformed

    private void cmdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdmActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_cmdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" LooN1 and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/looN1andfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd0;
    private javax.swing.JButton cmd1;
    private javax.swing.JButton cmd2;
    private javax.swing.JButton cmd3;
    private javax.swing.JButton cmd4;
    private javax.swing.JButton cmd5;
    private javax.swing.JButton cmd6;
    private javax.swing.JButton cmd7;
    private javax.swing.JButton cmd8;
    private javax.swing.JButton cmd9;
    private javax.swing.JButton cmda;
    private javax.swing.JButton cmdac;
    private javax.swing.JButton cmdb;
    private javax.swing.JButton cmdd;
    private javax.swing.JButton cmde;
    private javax.swing.JButton cmdm;
    private javax.swing.JButton cmdp;
    private javax.swing.JButton cmds;
    private javax.swing.JButton jButton13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
